repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
- repo: https://github.com/PyCQA/isort
  rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # frozen: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: b965c2a5026f8ba399283ba3e01898b012853c79  # frozen: 24.8.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: e43806be3607110919eff72939fda031776e885a  # frozen: 7.1.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/myint/docformatter
  rev: dfefe062799848234b4cd60b04aa633c0608025e  # frozen: v1.7.5
  hooks:
  - id: docformatter
- repo: https://github.com/executablebooks/mdformat
  rev: 08fba30538869a440b5059de90af03e3502e35fb  # frozen: 0.7.17
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-black
    - mdformat-toc
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d4911cfb7f1010759fde68da196036feeb25b99d  # frozen: v1.11.2
  hooks:
  - id: mypy
    args: ["--scripts-are-modules"]
    additional_dependencies:
    - python-dotenv
    - pytest
